### ISSUE TITLE
Amplify Console creating new buckets on every deployment

### ISSUE THREAD

**Issue by tscole** [awslabs/amplify-video#226]
Each time we deploy to our production environment a new input bucket (and sometimes - but not always output buckets are being created).

Build settings:

```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - npm install -g  amplify-category-video@3.3.0
    build:
      commands:
        - amplify plugin scan
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
