### ISSUE TITLE
Referencing video CF outputs

### ISSUE THREAD

**Issue by danielvouch** [awslabs/amplify-video#259]
** Which Category is your question related to? **
Amplify Video

** Provide additional details e.g. code snippets **
We need to reference our input bucket name in a lambda function, we have added a dependency in the `backend-config.json` file as follows with our video project name in place of "<video_resource_name>.

```
 {
    "category": "video",
    "resourceName": "<video_resource_name>",
    "attributes":  [
         "oVODInputS3"
    ]
}

```

We then added a parameter into our lambda CF template with the format <category><resource_name><attribute_name>.

```
"video<resource_name>oVODInputS3": {
     "Type": "String",
}

```

When pushing the changes up we are getting the following error

`UPDATE_FAILED      functionvcontroller           AWS::CloudFormation::Stack Mon May 17 2021 16:43:09 GMT+1000 (Australian Eastern Standard Time) Parameters: [video<resource_name>VODInputS3] must have values`

Is this the correct way to be referencing the outputs?

**Comment by danielvouch** [comment]
Update on this - after updating to the newest version of amplify-category-video this now works for `oVODInputS3` attribute.

However, when creating a custom directory and adding a new output attribute (oVODInputS3Arn) in the workflow-template we are getting the following error when pushing to the cloud - `Output 'oVODInputS3Arn' not found in stack`

```
Outputs:
  oVODInputS3:
    Description: Put source video here for processing and hosting by Amplify Video
    Value: !GetAtt rS3InputBucket.Outputs.oInputBucketName
  oVODInputS3Arn:
    Description: ARN for input bucket
    Value: !GetAtt rS3InputBucket.Outputs.oInputBucketArn
  oVODOutputS3:
    Description: Amplify Video hosts transcoded video content in this bucket
    Value: !GetAtt rS3OutputBucket.Outputs.oOutputBucketName
  oVodOutputUrl:
    Description: Amplify Video CloudFront Url
    Value: !GetAtt rCloudfrontDistribution.Outputs.oCFDomain

```
